# MCPRelay Configuration Example
# Copy this file to config.yaml and customize for your deployment

# Server settings
host: "0.0.0.0"
port: 8080
workers: 1
debug_mode: false

# CORS settings
allowed_origins:
  - "*"  # Restrict this in production

# MCP backend servers
servers:
  - name: "hue-server-1"
    url: "http://localhost:3000"
    weight: 1
    timeout: 30
    tags: ["hue", "lights", "production"]
  
  # Example of multiple servers for load balancing
  # - name: "hue-server-2"
  #   url: "http://localhost:3001"
  #   weight: 1
  #   timeout: 30
  #   tags: ["hue", "lights", "backup"]

# Load balancing strategy
load_balance_strategy: "round_robin"  # Options: round_robin, weighted_round_robin
health_check_interval: 30  # seconds

# Authentication
auth:
  enabled: true
  method: "api_key"  # Options: api_key, jwt
  jwt_algorithm: "HS256"
  jwt_secret: null  # Set this for JWT authentication
  api_keys:
    # Add your API keys here
    # admin: "your-secure-admin-key-here"
    # user1: "another-secure-key"

# Rate limiting
rate_limit:
  enabled: true
  default_requests_per_minute: 60
  burst_size: 10
  per_user_limits:
    # Override limits for specific users
    # admin: 300
    # premium_user: 120

# Security settings
mcp_safeguards_enabled: true  # Enable MCP request/response validation

# Redis (optional, for distributed rate limiting)
redis:
  enabled: false
  url: "redis://localhost:6379"
  db: 0
  prefix: "mcprelay:"

# Metrics and monitoring
metrics:
  enabled: true
  port: 9090
  path: "/metrics"

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "json"  # json, text
  access_log: true
  audit_log: true